//post
export const FETCH_POST_BY_ID = 'FETCH_POST_BY_ID';
export const FETCH_POSTS_BY_CATEGORY = 'FETCH_POSTS_BY_CATEGORY';
export const FETCH_POSTS_BY_CATEGORY_WITHPAGE = 'FETCH_POSTS_BY_CATEGORY_WITHPAGE';
export const FETCH_POSTS_BY_BLOGGER = 'FETCH_POSTS_BY_BLOGGER';
export const FETCH_POSTS_BY_BLOGGER_WITHPAGE = 'FETCH_POSTS_BY_BLOGGER_WITHPAGE';

//blogger
export const FETCH_BLOGGERS_BY_RANK = 'FETCH_BLOGGERS_BY_RANK';
export const FETCH_BLOGGERS_BY_KEY = 'FETCH_BLOGGERS_BY_KEY';
export const FETCH_BLOGGERS_BY_ID = 'FETCH_BLOGGERS_BY_ID';

//common
export const SHOW_TOAST = 'SHOW_TOAST';