//post
export const FETCH_POST_BY_ID = 'FETCH_POST_BY_ID';
export const FETCH_POSTS_BY_CATEGORY = 'FETCH_POSTS_BY_CATEGORY';
export const FETCH_POSTS_BY_CATEGORY_WITHPAGE = 'FETCH_POSTS_BY_CATEGORY_WITHPAGE';

//comment
export const FETCH_COMMENTS_BY_POST = 'FETCH_COMMENTS_BY_POST';
export const FETCH_COMMENTS_BY_POST_WITHPAGE = 'FETCH_COMMENTS_BY_POST_WITHPAGE';

//author
export const FETCH_AUTHORS_BY_RANK = 'FETCH_AUTHORS_BY_RANK';
export const FETCH_AUTHORS_BY_KEY = 'FETCH_AUTHORS_BY_KEY';
export const FETCH_AUTHOR_DETAIL = 'FETCH_AUTHOR_DETAIL';
export const FETCH_AUTHOR_DETAIL_WITHPAGE = 'FETCH_AUTHOR_DETAIL_WITHPAGE';

//common
export const SHOW_TOAST = 'SHOW_TOAST';