//post
export const FETCH_POST_BY_ID = 'FETCH_POST_BY_ID';
export const FETCH_POSTS_BY_CATEGORY = 'FETCH_POSTS_BY_CATEGORY';
export const FETCH_POSTS_BY_CATEGORY_WITHPAGE = 'FETCH_POSTS_BY_CATEGORY_WITHPAGE';

//comment
export const FETCH_COMMENTS_BY_POST = 'FETCH_COMMENTS_BY_POST';
export const FETCH_COMMENTS_BY_POST_WITHPAGE = 'FETCH_COMMENTS_BY_POST_WITHPAGE';

//author
export const FETCH_AUTHORS_BY_RANK = 'FETCH_AUTHORS_BY_RANK';
export const FETCH_AUTHORS_BY_KEY = 'FETCH_AUTHORS_BY_KEY';
export const FETCH_AUTHOR_DETAIL = 'FETCH_AUTHOR_DETAIL';
export const FETCH_AUTHOR_DETAIL_WITHPAGE = 'FETCH_AUTHOR_DETAIL_WITHPAGE';
export const CLEAR_AUTHOR_SEARCH_RESULT = 'CLEAR_AUTHOR_SEARCH_RESULT';

//common
export const SHOW_MESSAGE = 'SHOW_MESSAGE';

//config
export const UPDATE_CONFIG = 'UPDATE_CONFIG';
export const GET_CONFIG = 'GET_CONFIG';
export const REMOVE_CONFIG = 'REMOVE_CONFIG';

//offline
export const OFFLINE_POST_TO_STORAGE = 'OFFLINE_POST_TO_STORAGE';
export const GET_POSTS_FROM_STORAGE = 'GET_POSTS_FROM_STORAGE';
export const REMOVE_POSTS_IN_STORAGE = 'REMOVE_POSTS_IN_STORAGE';
export const REMOVE_POST_IN_STORAGE = 'REMOVE_POST_IN_STORAGE';
export const GET_POST_FROM_STORAGE = 'GET_POST_FROM_STORAGE';